# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/signal_detect_bd/signal_detect_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_detect_bd || ORIG_REF_NAME==signal_detect_bd} -quiet] -quiet

# IP: bd/signal_detect_bd/ip/signal_detect_bd_processing_system7_0_0/signal_detect_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_detect_bd_processing_system7_0_0 || ORIG_REF_NAME==signal_detect_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/signal_detect_bd/ip/signal_detect_bd_xbar_0/signal_detect_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_detect_bd_xbar_0 || ORIG_REF_NAME==signal_detect_bd_xbar_0} -quiet] -quiet

# IP: bd/signal_detect_bd/ip/signal_detect_bd_ps7_0_axi_periph_0/signal_detect_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_detect_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==signal_detect_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/signal_detect_bd/ip/signal_detect_bd_rst_ps7_0_50M_0/signal_detect_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_detect_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==signal_detect_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/signal_detect_bd/ip/signal_detect_bd_axi_gpio_0_2/signal_detect_bd_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_detect_bd_axi_gpio_0_2 || ORIG_REF_NAME==signal_detect_bd_axi_gpio_0_2} -quiet] -quiet

# IP: bd/signal_detect_bd/ip/signal_detect_bd_axi_gpio_0_3/signal_detect_bd_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_detect_bd_axi_gpio_0_3 || ORIG_REF_NAME==signal_detect_bd_axi_gpio_0_3} -quiet] -quiet

# IP: bd/signal_detect_bd/ip/signal_detect_bd_top_0_0/signal_detect_bd_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_detect_bd_top_0_0 || ORIG_REF_NAME==signal_detect_bd_top_0_0} -quiet] -quiet

# IP: bd/signal_detect_bd/ip/signal_detect_bd_auto_pc_0/signal_detect_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_detect_bd_auto_pc_0 || ORIG_REF_NAME==signal_detect_bd_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/suren/Documents/ECE_520/Final_Project/Sandbox/signal_detect_sb/signal_detect_sb.gen/sources_1/bd/signal_detect_bd/signal_detect_bd_ooc.xdc
