# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/suren/Documents/ECE_520/Final_Project/Sandbox/signal_detect_sb/signal_detect_sb.srcs/sources_1/bd/signal_detect_bd/ip/signal_detect_bd_processing_system7_0_0/signal_detect_bd_processing_system7_0_0.xci
# IP: The module: 'signal_detect_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/suren/Documents/ECE_520/Final_Project/Sandbox/signal_detect_sb/signal_detect_sb.gen/sources_1/bd/signal_detect_bd/ip/signal_detect_bd_processing_system7_0_0/signal_detect_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_detect_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/suren/Documents/ECE_520/Final_Project/Sandbox/signal_detect_sb/signal_detect_sb.srcs/sources_1/bd/signal_detect_bd/ip/signal_detect_bd_processing_system7_0_0/signal_detect_bd_processing_system7_0_0.xci
# IP: The module: 'signal_detect_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/suren/Documents/ECE_520/Final_Project/Sandbox/signal_detect_sb/signal_detect_sb.gen/sources_1/bd/signal_detect_bd/ip/signal_detect_bd_processing_system7_0_0/signal_detect_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_detect_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
